### PR TITLE
Add support for configuration options

### PR DESCRIPTION
**Pull request by doryphores**
This adds support for configuring the Jade engine.

### CODE REVIEW

**Comment by doryphores** [comment]
Hello? Anyone here?

**Comment by tantion** [comment]
+1

**Comment by NoahDragon** [comment]
Sorry for the late reply. Could you please re-submit the PR based on the newly change to Pug?

**Comment by yoshinorin** [comment]
@doryphores

Thank you for your PR.

We replaced this repo to [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug).
Please re-create a new PR at [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug).

Thanks :)

**Pull request closed without merging**
