### PR TITLE
release: 0.5.0

### PR DESCRIPTION
**Pull request by curbengh**
last release, mainly to publish the readme with deprecation message to npmjs.

### CODE REVIEW

**Review by yoshinorin — APPROVED** [review]

**Comment by YoshinoriN** [comment]
@curbengh 
Please don't forget to publish this with [deprecate command](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions).

**Comment by curbengh** [comment]
yep, actually I was about to npm-deprecate before this PR, then I remembered the npm's readme is not updated yet.

**Comment by curbengh** [comment]
https://www.npmjs.com/package/hexo-renderer-jade/v/0.5.0

also deprecated the npm package.

**Comment by curbengh** [comment]
@YoshinoriN 
Please archive this repo.

**Pull request merged**
